server:
  port: 8081

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}

simpleservice:
  ribbon:
    # not used by RestTemplate with ribbon-eureka
    #listOfServers: localhost:8081, localhost:8083
    #NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList

    # the eureka vipAddress of the target service (Disabled)
    DeploymentContextBasedVipAddresses: simpleservice

spring:
  boot:
    admin:
      url: http://localhost:7070/
  cloud:
    config:
      enabled: false
      failFast: true
#      uri: ${CONFIG_SERVICE_URI:http://localhost:9090/}
      discovery:
        enabled: true
        serviceId: configserver

zuul:
  routes:
    simpleservice: /zuulsimpleservice/**
