server:
  port: 8090

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}

spring:
  boot:
    admin:
      url: http://localhost:7070/
  cloud:
    config:
      enabled: true
      failFast: true
#      uri: ${CONFIG_SERVICE_URI:http://localhost:9090/}
      discovery:
        enabled: true
        serviceId: configserver